### ISSUE TITLE
Error Loading English conversation

### ISSUE THREAD

**Issue by suramrit** [mowolf/ChatAnalyzer#1]
#redirected here from reddit

When trying to open a .txt English conversation, Im getting the following error. 
Cannot read property 'message' of undefined at analyze.js:77

**Comment by SebRut** [comment]
I get the same issue with a german conversation.

**Comment by mtuit** [comment]
If your format is like this: DD/MM/YYYY, HH:MM - Name: Message, then you can use the quick work-around I wrote to fix this in my fork. My code is only compatible with this format. @mowolf Feel free to use it when you want to add support for multiple formats (also fixed some bugs).

**Comment by daanhaitsma** [comment]
@mtuit My export has that format, but I get the same error using your repo

**Comment by andtos90** [comment]
I also developed a similar solution to the @mtuit, you can find it here: https://github.com/andtos90/ChatAnalyzer. With more examples in different languages this could be solved easily

**Comment by mtuit** [comment]
@daanhaitsma That's odd. The following (small) test file should work and is in the same format. Could you try if this file works for you? 
[testWhatsappGesprek.txt](https://github.com/mowolf/ChatAnalyzer/files/1958799/testWhatsappGesprek.txt)

**Comment by mowolf** [comment]
I am currently updating the code. Will work soon!

**Comment by mowolf** [comment]
Fixed it and added support to all the formats mentioned in the reddid thread. In case your format does not work please open another issue!
