### ISSUE TITLE
Add Group support

### ISSUE THREAD

**Issue by ryanb93** [mowolf/ChatAnalyzer#12]
Groups are not supported at the moment.

**Comment by mowolf** [comment]
@ryanb93 Any ideas on how to present all the data? I think it would make sense to have a bit different graphs for groups.

**Comment by ryanb93** [comment]
@mowolf perhaps flip the users from horizontal to vertically stacked.

Something like:

User | Messages sent | Words per Message | Pictures sent
---- | -------------|------|------|
 John Smith  | 5012 | 42 | 500 
 Paul Smith  | 1122 | 46 | 4 
 Wilson Smith  | 3012 | 12 | 66 
 Chris Smith  | 5442 | 43 | 45 
 Phil Smith  | 20 | 42 | 12

**Comment by mowolf** [comment]
Thats a good idea. Also thought about adding some kind of funny sentences to the people.
E.g. the person with the most words: "XY can't stop to chat." 
the person with the least words: "XZ seems bored."

**Comment by mowolf** [comment]
@ryanb93 I added group support. Currently it's just a table with all the info. Working on adding a graph as well!
