### ISSUE TITLE
Picture Count only works for some languages

### ISSUE THREAD

**Issue by ryanb93** [mowolf/ChatAnalyzer#13]
Pictures sent is always 0 (French)

**Comment by mowolf** [comment]
The problem is that we need the image tag for every language.
in german it is: <Bild weggelassen>
I need to find a list of these identifiers so that it works with all languages

**Comment by ryanb93** [comment]
Could always export _with_ photos attached and that replaces the `<Bild weggelassen>` with `[25/07/2017, 09:17:15] Ryan: 2017-07-25-PHOTO-00000043.jpg <‎attached>`. Then you could check for common image file names (`jpg`, `jpeg`, `png`, `gif`).

**Comment by mowolf** [comment]
@ryanb93 Yep that would be a good workaround. Will add that, but keep the checking for the identifies there as well.

The only problem I see with exporting with media, is that the export for a chat that has a lot of images (like 2000+) is not really working smoothly with WhattsApp.

**Comment by mowolf** [comment]
added a general config to `analyze.js`. added a description how to add these identifiers in `README.me`. I ve also added `<‎attached>` to the identifiers. **This probably results that all media will be counted as a picture.**

**Comment by mowolf** [comment]
https://github.com/mowolf/ChatAnalyzer/commit/cf8f3ce62940fc0c08e188304033064ff87aa96d
