### ISSUE TITLE
contents[i] is undefined

### ISSUE THREAD

**Issue by JoKrus** [mowolf/ChatAnalyzer#2]
if i select a file i get a TypeError contents[i] undefined in analyze.js:77

**Comment by Bennik2000** [comment]
I digged a little bit into the code and found that it expects a differen formatting than generated by my Whatsapp client:
```
// Format for normal message:
// [09.04.18, 10:19:36] Name: MESSAGE
// announcments do not have a ":" and should be deleted
```
The Format of my chat log is 

09.04.18, 10:19 - Name: MESSAGE

**Comment by mowolf** [comment]
same error as https://github.com/mowolf/ChatAnalyzer/issues/1
