### ISSUE TITLE
whatsapp bot secured messages considered as a user

### ISSUE THREAD

**Issue by Nilegfx** [mowolf/ChatAnalyzer#29]
HI Moritz, 

I liked the idea, I've a lot to think about how to improve this, I'll try to help as much as I can to improve my analysis skills. 

my first catch is:

```7/6/16, 3:50 AM - Messages to this chat and calls are now secured with end-to-end encryption. Tap for more info.```

this line needs to be handled probably as now it considers it as a user.

I'll try to work on this one.

**Comment by mowolf** [comment]
Oh yeah. I know why this happens. The regex to find names searches for „-„ and „:“ (bc of different formats). If you want to fix that you can either run two different regexes (one with „:“ and one with „-„) and then take the results of the regex which has more matches. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mowolf** [comment]
@Nilegfx please see [this commit](https://github.com/mowolf/ChatAnalyzer/commit/04e3ca3b337042d9f76b2d4994557c3751404769). Names that get detected, that have less then two messages get removed with this. 

This should fix this problem most of the time.
