### ISSUE TITLE
Not looking at articles

### ISSUE THREAD

**Issue by ludoro** [mowolf/ChatAnalyzer#33]
Is still this under development? I would love to help around! For example: I do not think that looking at articles is very interesting, shouldn't we skip that?

**Comment by mowolf** [comment]
Hey @ludoro, there is actually still stuff to do! Currently I do have nearly no time that I can spent toward this project however. 

However the code is not that understandable as it is not documented at all. What are you looking to do?

**Comment by ludoro** [comment]
Nice to hear! I was thinking about some kind of sentiment analysis on the texts, does that sound cool?

**Comment by mowolf** [comment]
YEAH! That sounds great! Thought about that as well! I would be open to explain you understand the current code if you dont get it yourself to get you access to the data you would need for that analysis. If you want to do that you are more then welcome!

**Comment by ludoro** [comment]
Nice. I will take a look into it and get back to you if I get into problems.
